import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'character-role',
  title: { en: 'Character Role', uk: 'Роль персонажа' },
  description: {
    en: 'Use to define a character\'s background or generate a random encounter.',
    uk: 'Визначає передісторію персонажа або генерує випадкову зустріч.',
  },
  rows: {
    en: [
      { min: 1,  max: 2,  result: 'Criminal' },
      { min: 3,  max: 4,  result: 'Healer' },
      { min: 5,  max: 6,  result: 'Bandit' },
      { min: 7,  max: 9,  result: 'Guide' },
      { min: 10, max: 12, result: 'Performer' },
      { min: 13, max: 15, result: 'Miner' },
      { min: 16, max: 18, result: 'Mercenary' },
      { min: 19, max: 21, result: 'Outcast' },
      { min: 22, max: 24, result: 'Vagrant' },
      { min: 25, max: 27, result: 'Forester' },
      { min: 28, max: 30, result: 'Traveler' },
      { min: 31, max: 33, result: 'Mystic' },
      { min: 34, max: 36, result: 'Priest' },
      { min: 37, max: 39, result: 'Sailor' },
      { min: 40, max: 42, result: 'Pilgrim' },
      { min: 43, max: 45, result: 'Thief' },
      { min: 46, max: 48, result: 'Adventurer' },
      { min: 49, max: 51, result: 'Forager' },
      { min: 52, max: 54, result: 'Leader' },
      { min: 55, max: 58, result: 'Guard' },
      { min: 59, max: 62, result: 'Artisan' },
      { min: 63, max: 66, result: 'Scout' },
      { min: 67, max: 70, result: 'Herder' },
      { min: 71, max: 74, result: 'Fisher' },
      { min: 75, max: 79, result: 'Warrior' },
      { min: 80, max: 84, result: 'Hunter' },
      { min: 85, max: 89, result: 'Raider' },
      { min: 90, max: 94, result: 'Trader' },
      { min: 95, max: 99, result: 'Farmer' },
      { min: 100, max: 100, result: 'Unusual role' },
    ],
    uk: [
      { min: 1,  max: 2,  result: 'Злочинець' },
      { min: 3,  max: 4,  result: 'Цілитель' },
      { min: 5,  max: 6,  result: 'Бандит' },
      { min: 7,  max: 9,  result: 'Провідник' },
      { min: 10, max: 12, result: 'Виконавець' },
      { min: 13, max: 15, result: 'Шахтар' },
      { min: 16, max: 18, result: 'Найманець' },
      { min: 19, max: 21, result: 'Вигнанець' },
      { min: 22, max: 24, result: 'Волоцюга' },
      { min: 25, max: 27, result: 'Лісник' },
      { min: 28, max: 30, result: 'Мандрівник' },
      { min: 31, max: 33, result: 'Містик' },
      { min: 34, max: 36, result: 'Жрець' },
      { min: 37, max: 39, result: 'Моряк' },
      { min: 40, max: 42, result: 'Паломник' },
      { min: 43, max: 45, result: 'Злодій' },
      { min: 46, max: 48, result: 'Шукач пригод' },
      { min: 49, max: 51, result: 'Збирач' },
      { min: 52, max: 54, result: 'Лідер' },
      { min: 55, max: 58, result: 'Охоронець' },
      { min: 59, max: 62, result: 'Ремісник' },
      { min: 63, max: 66, result: 'Розвідник' },
      { min: 67, max: 70, result: 'Пастух' },
      { min: 71, max: 74, result: 'Рибалка' },
      { min: 75, max: 79, result: 'Воїн' },
      { min: 80, max: 84, result: 'Мисливець' },
      { min: 85, max: 89, result: 'Нападник' },
      { min: 90, max: 94, result: 'Торговець' },
      { min: 95, max: 99, result: 'Фермер' },
      { min: 100, max: 100, result: 'Незвичайна роль' },
    ],
  },
};

export default oracle;
