import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'mystic-backlash',
  title: { en: 'Mystic Backlash', uk: 'Містична віддача' },
  description: {
    en: 'Use when a ritual fails or magic goes wrong. Can supplement or replace "Pay the Price".',
    uk: 'Використовуйте при провалі ритуалу або негативній взаємодії з містичними силами.',
  },
  rows: {
    en: [
      { min: 1,  max: 4,  result: 'Your ritual has the opposite affect.' },
      { min: 5,  max: 8,  result: 'You are sapped of strength.' },
      { min: 9,  max: 12, result: 'Your friend, ally, or companion is adversely affected.' },
      { min: 13, max: 16, result: 'You destroy an important object.' },
      { min: 17, max: 20, result: 'You inadvertently summon a horror.' },
      { min: 21, max: 24, result: 'You collapse, and drift into a troubled sleep.' },
      { min: 25, max: 28, result: 'You undergo a physical torment which leaves its mark upon you.' },
      { min: 29, max: 32, result: 'You hear ghostly voices whispering of dark portents.' },
      { min: 33, max: 36, result: 'You are lost in shadow, and find yourself in another place without memory of how you got there.' },
      { min: 37, max: 40, result: 'You alert someone or something to your presence.' },
      { min: 41, max: 44, result: 'You are not yourself, and act against a friend, ally, or companion.' },
      { min: 45, max: 48, result: 'You affect or damage your surroundings, causing a disturbance or potential harm.' },
      { min: 49, max: 52, result: 'You waste resources.' },
      { min: 53, max: 56, result: 'You suffer the loss of a sense for several hours.' },
      { min: 57, max: 60, result: 'You lose your connection to magic for a day or so, and cannot perform rituals.' },
      { min: 61, max: 64, result: 'Your ritual affects the target in an unexpected and problematic way.' },
      { min: 65, max: 68, result: 'Your ritual reveals a surprising and troubling truth.' },
      { min: 69, max: 72, result: 'You are tempted by dark powers.' },
      { min: 73, max: 76, result: 'You see a troubling vision of your future.' },
      { min: 77, max: 80, result: 'You can\'t perform this ritual again until you acquire an important component.' },
      { min: 81, max: 84, result: 'You develop a strange fear or compulsion.' },
      { min: 85, max: 88, result: 'Your ritual causes creatures to exhibit strange or aggressive behavior.' },
      { min: 89, max: 92, result: 'You are tormented by an apparition from your past.' },
      { min: 93, max: 96, result: 'You are wracked with sudden sickness.' },
      { min: 97, max: 100, result: 'Roll twice more. Both results occur. If the same, make it worse.', rollAgain: 2 },
    ],
    uk: [
      { min: 1,  max: 4,  result: 'Ваш ритуал має протилежний ефект.' },
      { min: 5,  max: 8,  result: 'Вас позбавлено сил.' },
      { min: 9,  max: 12, result: 'Ваш друг, союзник або супутник постраждав від негативного впливу.' },
      { min: 13, max: 16, result: 'Ви знищуєте важливий предмет.' },
      { min: 17, max: 20, result: 'Ви випадково викликаєте жах.' },
      { min: 21, max: 24, result: 'Ви втрачаєте свідомість і провалюєтесь у неспокійний сон.' },
      { min: 25, max: 28, result: 'Ви зазнаєте фізичної муки, яка залишає свій слід на вас.' },
      { min: 29, max: 32, result: 'Ви чуєте примарні голоси, які шепочуть про темні знамення.' },
      { min: 33, max: 36, result: 'Ви губитеся в тіні і опиняєтеся в іншому місці, не пам\'ятаючи, як ви туди потрапили.' },
      { min: 37, max: 40, result: 'Ви попереджаєте когось або щось про свою присутність.' },
      { min: 41, max: 44, result: 'Ви самі не свої і дієте проти друга, союзника або супутника.' },
      { min: 45, max: 48, result: 'Ви впливаєте або завдаєте шкоди своєму оточенню, викликаючи занепокоєння або потенційну небезпеку.' },
      { min: 49, max: 52, result: 'Ви витрачаєте ресурси.' },
      { min: 53, max: 56, result: 'Ви втрачаєте одне з відчуттів на кілька годин.' },
      { min: 57, max: 60, result: 'Ви втрачаєте зв\'язок з магією на день чи близько того і не можете виконувати ритуали.' },
      { min: 61, max: 64, result: 'Ваш ритуал впливає на ціль несподіваним і проблематичним чином.' },
      { min: 65, max: 68, result: 'Ваш ритуал розкриває дивовижну і тривожну правду.' },
      { min: 69, max: 72, result: 'Вас спокушають темні сили.' },
      { min: 73, max: 76, result: 'Ви бачите тривожне видіння свого майбутнього.' },
      { min: 77, max: 80, result: 'Ви не можете повторити цей ритуал, поки не придбаєте важливий компонент.' },
      { min: 81, max: 84, result: 'У вас розвивається дивний страх або манія.' },
      { min: 85, max: 88, result: 'Ваш ритуал змушує істот проявляти дивну або агресивну поведінку.' },
      { min: 89, max: 92, result: 'Вас мучить привид з вашого минулого.' },
      { min: 93, max: 96, result: 'Вас вражає раптова хвороба.' },
      { min: 97, max: 100, result: 'Киньте ще двічі. Обидва результати відбуваються. Якщо збігаються — зробіть гірше.', rollAgain: 2 },
    ],
  },
};

export default oracle;
