import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'location',
  title: { en: 'Location', uk: 'Локація' },
  description: {
    en: 'Use when traveling to generate a point-of-interest or answer a question about a place.',
    uk: 'Під час подорожі для генерації орієнтира або відповіді на запитання про місце.',
  },
  rows: {
    en: [
      { min: 1,  max: 1,  result: 'Hideout' },
      { min: 2,  max: 2,  result: 'Ruin' },
      { min: 3,  max: 3,  result: 'Mine' },
      { min: 4,  max: 4,  result: 'Waste' },
      { min: 5,  max: 5,  result: 'Mystical Site' },
      { min: 6,  max: 6,  result: 'Path' },
      { min: 7,  max: 7,  result: 'Outpost' },
      { min: 8,  max: 8,  result: 'Wall' },
      { min: 9,  max: 9,  result: 'Battlefield' },
      { min: 10, max: 10, result: 'Hovel' },
      { min: 11, max: 11, result: 'Spring' },
      { min: 12, max: 12, result: 'Lair' },
      { min: 13, max: 13, result: 'Fort' },
      { min: 14, max: 14, result: 'Bridge' },
      { min: 15, max: 15, result: 'Camp' },
      { min: 16, max: 16, result: 'Cairn/Grave' },
      { min: 17, max: 18, result: 'Caravan' },
      { min: 19, max: 20, result: 'Waterfall' },
      { min: 21, max: 22, result: 'Cave' },
      { min: 23, max: 24, result: 'Swamp' },
      { min: 25, max: 26, result: 'Fen' },
      { min: 27, max: 28, result: 'Ravine' },
      { min: 29, max: 30, result: 'Road' },
      { min: 31, max: 32, result: 'Tree' },
      { min: 33, max: 34, result: 'Pond' },
      { min: 35, max: 36, result: 'Fields' },
      { min: 37, max: 38, result: 'Marsh' },
      { min: 39, max: 40, result: 'Steading' },
      { min: 41, max: 42, result: 'Rapids' },
      { min: 43, max: 44, result: 'Pass' },
      { min: 45, max: 46, result: 'Trail' },
      { min: 47, max: 48, result: 'Glade' },
      { min: 49, max: 50, result: 'Plain' },
      { min: 51, max: 52, result: 'Ridge' },
      { min: 53, max: 54, result: 'Cliff' },
      { min: 55, max: 56, result: 'Grove' },
      { min: 57, max: 58, result: 'Village' },
      { min: 59, max: 60, result: 'Moor' },
      { min: 61, max: 62, result: 'Thicket' },
      { min: 63, max: 64, result: 'River Ford' },
      { min: 65, max: 66, result: 'Valley' },
      { min: 67, max: 68, result: 'Bay/Fjord' },
      { min: 69, max: 70, result: 'Foothills' },
      { min: 71, max: 72, result: 'Lake' },
      { min: 73, max: 75, result: 'River' },
      { min: 76, max: 79, result: 'Forest' },
      { min: 80, max: 83, result: 'Coast' },
      { min: 84, max: 88, result: 'Hill' },
      { min: 89, max: 93, result: 'Mountain' },
      { min: 94, max: 99, result: 'Woods' },
      { min: 100, max: 100, result: 'Anomaly' },
    ],
    uk: [
      { min: 1,  max: 1,  result: 'Схованка' },
      { min: 2,  max: 2,  result: 'Руїни' },
      { min: 3,  max: 3,  result: 'Копальня' },
      { min: 4,  max: 4,  result: 'Пустош' },
      { min: 5,  max: 5,  result: 'Містичне місце' },
      { min: 6,  max: 6,  result: 'Стежка' },
      { min: 7,  max: 7,  result: 'Застава' },
      { min: 8,  max: 8,  result: 'Стіна' },
      { min: 9,  max: 9,  result: 'Поле бою' },
      { min: 10, max: 10, result: 'Халупа' },
      { min: 11, max: 11, result: 'Джерело' },
      { min: 12, max: 12, result: 'Лігво' },
      { min: 13, max: 13, result: 'Форт' },
      { min: 14, max: 14, result: 'Міст' },
      { min: 15, max: 15, result: 'Табір' },
      { min: 16, max: 16, result: 'Курган/Могила' },
      { min: 17, max: 18, result: 'Караван' },
      { min: 19, max: 20, result: 'Водоспад' },
      { min: 21, max: 22, result: 'Печера' },
      { min: 23, max: 24, result: 'Болото' },
      { min: 25, max: 26, result: 'Трясовина' },
      { min: 27, max: 28, result: 'Яр' },
      { min: 29, max: 30, result: 'Дорога' },
      { min: 31, max: 32, result: 'Дерево' },
      { min: 33, max: 34, result: 'Ставок' },
      { min: 35, max: 36, result: 'Поля' },
      { min: 37, max: 38, result: 'Драговина' },
      { min: 39, max: 40, result: 'Обладнаний двір' },
      { min: 41, max: 42, result: 'Пороги' },
      { min: 43, max: 44, result: 'Перевал' },
      { min: 45, max: 46, result: 'Шлях' },
      { min: 47, max: 48, result: 'Галявина' },
      { min: 49, max: 50, result: 'Рівнина' },
      { min: 51, max: 52, result: 'Гірський хребет' },
      { min: 53, max: 54, result: 'Скеля (Кліф)' },
      { min: 55, max: 56, result: 'Гай' },
      { min: 57, max: 58, result: 'Село' },
      { min: 59, max: 60, result: 'Вересове пустище' },
      { min: 61, max: 62, result: 'Хащі' },
      { min: 63, max: 64, result: 'Річковий брід' },
      { min: 65, max: 66, result: 'Долина' },
      { min: 67, max: 68, result: 'Затока/Фіорд' },
      { min: 69, max: 70, result: 'Передгір\'я' },
      { min: 71, max: 72, result: 'Озеро' },
      { min: 73, max: 75, result: 'Річка' },
      { min: 76, max: 79, result: 'Ліс' },
      { min: 80, max: 83, result: 'Узбережжя' },
      { min: 84, max: 88, result: 'Пагорб' },
      { min: 89, max: 93, result: 'Гора' },
      { min: 94, max: 99, result: 'Хащі (Лісисті)' },
      { min: 100, max: 100, result: 'Аномалія' },
    ],
  },
};

export default oracle;
