import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'location-descriptor',
  title: { en: 'Location Descriptor', uk: 'Опис локації' },
  description: {
    en: 'Add detail to a location result, or generate a standalone description. Roll multiple times for more detail.',
    uk: 'Додає деталі до локації. Можна кидати кілька разів для додаткових деталей.',
  },
  rows: {
    en: [
      { min: 1,   max: 2,  result: 'High' },
      { min: 3,   max: 4,  result: 'Remote' },
      { min: 5,   max: 6,  result: 'Exposed' },
      { min: 7,   max: 8,  result: 'Small' },
      { min: 9,   max: 10, result: 'Broken' },
      { min: 11,  max: 12, result: 'Diverse' },
      { min: 13,  max: 14, result: 'Rough' },
      { min: 15,  max: 16, result: 'Dark' },
      { min: 17,  max: 18, result: 'Shadowy' },
      { min: 19,  max: 20, result: 'Contested' },
      { min: 21,  max: 22, result: 'Grim' },
      { min: 23,  max: 24, result: 'Wild' },
      { min: 25,  max: 26, result: 'Fertile' },
      { min: 27,  max: 28, result: 'Blocked' },
      { min: 29,  max: 30, result: 'Ancient' },
      { min: 31,  max: 32, result: 'Perilous' },
      { min: 33,  max: 34, result: 'Hidden' },
      { min: 35,  max: 36, result: 'Occupied' },
      { min: 37,  max: 38, result: 'Rich' },
      { min: 39,  max: 40, result: 'Big' },
      { min: 41,  max: 42, result: 'Savage' },
      { min: 43,  max: 44, result: 'Defended' },
      { min: 45,  max: 46, result: 'Withered' },
      { min: 47,  max: 48, result: 'Mystical' },
      { min: 49,  max: 50, result: 'Inaccessible' },
      { min: 51,  max: 52, result: 'Protected' },
      { min: 53,  max: 54, result: 'Abandoned' },
      { min: 55,  max: 56, result: 'Wide' },
      { min: 57,  max: 58, result: 'Foul' },
      { min: 59,  max: 60, result: 'Dead' },
      { min: 61,  max: 62, result: 'Ruined' },
      { min: 63,  max: 64, result: 'Barren' },
      { min: 65,  max: 66, result: 'Cold' },
      { min: 67,  max: 68, result: 'Blighted' },
      { min: 69,  max: 70, result: 'Low' },
      { min: 71,  max: 72, result: 'Beautiful' },
      { min: 73,  max: 74, result: 'Abundant' },
      { min: 75,  max: 76, result: 'Lush' },
      { min: 77,  max: 78, result: 'Flooded' },
      { min: 79,  max: 80, result: 'Empty' },
      { min: 81,  max: 82, result: 'Strange' },
      { min: 83,  max: 84, result: 'Corrupted' },
      { min: 85,  max: 86, result: 'Peaceful' },
      { min: 87,  max: 88, result: 'Forgotten' },
      { min: 89,  max: 90, result: 'Expansive' },
      { min: 91,  max: 92, result: 'Settled' },
      { min: 93,  max: 94, result: 'Dense' },
      { min: 95,  max: 96, result: 'Civilized' },
      { min: 97,  max: 98, result: 'Desolate' },
      { min: 99,  max: 100, result: 'Isolated' },
    ],
    uk: [
      { min: 1,   max: 2,  result: 'Високий' },
      { min: 3,   max: 4,  result: 'Віддалений' },
      { min: 5,   max: 6,  result: 'Відкритий' },
      { min: 7,   max: 8,  result: 'Малий' },
      { min: 9,   max: 10, result: 'Зламаний' },
      { min: 11,  max: 12, result: 'Різноманітний' },
      { min: 13,  max: 14, result: 'Нерівний' },
      { min: 15,  max: 16, result: 'Темний' },
      { min: 17,  max: 18, result: 'Тіньовий' },
      { min: 19,  max: 20, result: 'Спірний' },
      { min: 21,  max: 22, result: 'Похмурий' },
      { min: 23,  max: 24, result: 'Дикий (Природний)' },
      { min: 25,  max: 26, result: 'Родючий' },
      { min: 27,  max: 28, result: 'Заблокований' },
      { min: 29,  max: 30, result: 'Стародавній' },
      { min: 31,  max: 32, result: 'Небезпечний' },
      { min: 33,  max: 34, result: 'Прихований' },
      { min: 35,  max: 36, result: 'Зайнятий' },
      { min: 37,  max: 38, result: 'Багатий' },
      { min: 39,  max: 40, result: 'Великий' },
      { min: 41,  max: 42, result: 'Дикий (Жорстокий)' },
      { min: 43,  max: 44, result: 'Захищений' },
      { min: 45,  max: 46, result: 'Зів\'ялий' },
      { min: 47,  max: 48, result: 'Містичний' },
      { min: 49,  max: 50, result: 'Недоступний' },
      { min: 51,  max: 52, result: 'Охоронюваний' },
      { min: 53,  max: 54, result: 'Покинутий' },
      { min: 55,  max: 56, result: 'Широкий' },
      { min: 57,  max: 58, result: 'Мерзенний' },
      { min: 59,  max: 60, result: 'Мертвий' },
      { min: 61,  max: 62, result: 'Зруйнований' },
      { min: 63,  max: 64, result: 'Безплідний' },
      { min: 65,  max: 66, result: 'Холодний' },
      { min: 67,  max: 68, result: 'Заражений' },
      { min: 69,  max: 70, result: 'Низький' },
      { min: 71,  max: 72, result: 'Красивий' },
      { min: 73,  max: 74, result: 'Достатній' },
      { min: 75,  max: 76, result: 'Пишний' },
      { min: 77,  max: 78, result: 'Затоплений' },
      { min: 79,  max: 80, result: 'Порожній' },
      { min: 81,  max: 82, result: 'Дивний' },
      { min: 83,  max: 84, result: 'Спотворений' },
      { min: 85,  max: 86, result: 'Мирний' },
      { min: 87,  max: 88, result: 'Забутий' },
      { min: 89,  max: 90, result: 'Обширний' },
      { min: 91,  max: 92, result: 'Заселений' },
      { min: 93,  max: 94, result: 'Густий' },
      { min: 95,  max: 96, result: 'Цивілізований' },
      { min: 97,  max: 98, result: 'Спустошений' },
      { min: 99,  max: 100, result: 'Ізольований' },
    ],
  },
};

export default oracle;
