import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'major-plot-twist',
  title: { en: 'Major Plot Twist', uk: 'Значимі повороти сюжету' },
  description: {
    en: 'Use to introduce a surprise or revelation. Effective when resolving a match on challenge dice.',
    uk: 'Вводить сюрприз або одкровення. Ефективно для вирішення дублів на граниках виклику.',
  },
  rows: {
    en: [
      { min: 1,  max: 5,  result: 'It was all a diversion.' },
      { min: 6,  max: 10, result: 'A dark secret is revealed.' },
      { min: 11, max: 15, result: 'A trap is sprung.' },
      { min: 16, max: 20, result: 'An assumption is revealed to be false.' },
      { min: 21, max: 25, result: 'A secret alliance is revealed.' },
      { min: 26, max: 30, result: 'Your actions benefit an enemy.' },
      { min: 31, max: 35, result: 'Someone returns unexpectedly.' },
      { min: 36, max: 40, result: 'A more dangerous foe is revealed.' },
      { min: 41, max: 45, result: 'You and an enemy share a common goal.' },
      { min: 46, max: 50, result: 'A true identity is revealed.' },
      { min: 51, max: 55, result: 'You are betrayed by someone who was trusted.' },
      { min: 56, max: 60, result: 'You are too late.' },
      { min: 61, max: 65, result: 'The true enemy is revealed.' },
      { min: 66, max: 70, result: 'The enemy gains new allies.' },
      { min: 71, max: 75, result: 'A new danger appears.' },
      { min: 76, max: 80, result: 'Someone or something goes missing.' },
      { min: 81, max: 85, result: 'The truth of a relationship is revealed.' },
      { min: 86, max: 90, result: 'Two seemingly unrelated situations are shown to be connected.' },
      { min: 91, max: 95, result: 'Unexpected powers or abilities are revealed.' },
      { min: 96, max: 100, result: 'Roll twice more. Both results occur. If the same, make it more dramatic.', rollAgain: 2 },
    ],
    uk: [
      { min: 1,  max: 5,  result: 'Все це було лише відволікаючим маневром.' },
      { min: 6,  max: 10, result: 'Темна таємниця розкрита.' },
      { min: 11, max: 15, result: 'Пастка спрацювала.' },
      { min: 16, max: 20, result: 'Припущення виявилося хибним.' },
      { min: 21, max: 25, result: 'Таємний альянс розкритий.' },
      { min: 26, max: 30, result: 'Ваші дії приносять користь ворогу.' },
      { min: 31, max: 35, result: 'Хтось несподівано повертається.' },
      { min: 36, max: 40, result: 'З\'являється більш небезпечний ворог.' },
      { min: 41, max: 45, result: 'Ви та ворог маєте спільну мету.' },
      { min: 46, max: 50, result: 'Справжня особистість розкрита.' },
      { min: 51, max: 55, result: 'Вас зраджує той, кому ви довіряли.' },
      { min: 56, max: 60, result: 'Ви запізнилися.' },
      { min: 61, max: 65, result: 'Справжній ворог викритий.' },
      { min: 66, max: 70, result: 'Ворог отримує нових союзників.' },
      { min: 71, max: 75, result: 'З\'являється нова небезпека.' },
      { min: 76, max: 80, result: 'Хтось або щось зникає.' },
      { min: 81, max: 85, result: 'Розкривається правда про стосунки.' },
      { min: 86, max: 90, result: 'Дві, на перший погляд, не пов\'язані ситуації виявляються пов\'язаними.' },
      { min: 91, max: 95, result: 'Несподівані сили або здібності розкриті.' },
      { min: 96, max: 100, result: 'Киньте ще двічі. Обидва результати відбуваються. Якщо збігаються — зробіть більш драматичним.', rollAgain: 2 },
    ],
  },
};

export default oracle;
