import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'elf-names',
  title: { en: 'Elf Names', uk: 'Імена ельфів' },
  description: {
    en: 'Use to generate a name for an elf character.',
    uk: 'Для генерації імені ельфійського персонажа.',
  },
  rows: {
    en: [
      { min: 1,   max: 2,  result: 'Arsula' },
      { min: 3,   max: 4,  result: 'Naidita' },
      { min: 5,   max: 6,  result: 'Belesunna' },
      { min: 7,   max: 8,  result: 'Vidarna' },
      { min: 9,   max: 10, result: 'Ninsunu' },
      { min: 11,  max: 12, result: 'Balathu' },
      { min: 13,  max: 14, result: 'Dorosi' },
      { min: 15,  max: 16, result: 'Gezera' },
      { min: 17,  max: 18, result: 'Zursan' },
      { min: 19,  max: 20, result: 'Seleeku' },
      { min: 21,  max: 22, result: 'Utamara' },
      { min: 23,  max: 24, result: 'Nebakay' },
      { min: 25,  max: 26, result: 'Dismashk' },
      { min: 27,  max: 28, result: 'Mitunu' },
      { min: 29,  max: 30, result: 'Atani' },
      { min: 31,  max: 32, result: 'Kinzura' },
      { min: 33,  max: 34, result: 'Sumula' },
      { min: 35,  max: 36, result: 'Ukames' },
      { min: 37,  max: 38, result: 'Ahmeshki' },
      { min: 39,  max: 40, result: 'Ilsit' },
      { min: 41,  max: 42, result: 'Mayatanay' },
      { min: 43,  max: 44, result: 'Etana' },
      { min: 45,  max: 46, result: 'Gamanna' },
      { min: 47,  max: 48, result: 'Nessana' },
      { min: 49,  max: 50, result: 'Uralar' },
      { min: 51,  max: 52, result: 'Tishetu' },
      { min: 53,  max: 54, result: 'Leucia' },
      { min: 55,  max: 56, result: 'Sutahe' },
      { min: 57,  max: 58, result: 'Dotani' },
      { min: 59,  max: 60, result: 'Uktannu' },
      { min: 61,  max: 62, result: 'Retenay' },
      { min: 63,  max: 64, result: 'Kendalanu' },
      { min: 65,  max: 66, result: 'Tahuta' },
      { min: 67,  max: 68, result: 'Mattissa' },
      { min: 69,  max: 70, result: 'Anatu' },
      { min: 71,  max: 72, result: 'Aralu' },
      { min: 73,  max: 74, result: 'Arakhi' },
      { min: 75,  max: 76, result: 'Ibrahem' },
      { min: 77,  max: 78, result: 'Sinosu' },
      { min: 79,  max: 80, result: 'Jemshida' },
      { min: 81,  max: 82, result: 'Visapni' },
      { min: 83,  max: 84, result: 'Hullata' },
      { min: 85,  max: 86, result: 'Sidura' },
      { min: 87,  max: 88, result: 'Kerihu' },
      { min: 89,  max: 90, result: 'Ereshki' },
      { min: 91,  max: 92, result: 'Cybela' },
      { min: 93,  max: 94, result: 'Anunna' },
      { min: 95,  max: 96, result: 'Otani' },
      { min: 97,  max: 98, result: 'Ditani' },
      { min: 99,  max: 100, result: 'Faraza' },
    ],
    uk: [
      { min: 1,   max: 2,  result: 'Арсула' },
      { min: 3,   max: 4,  result: 'Наідіта' },
      { min: 5,   max: 6,  result: 'Белесунна' },
      { min: 7,   max: 8,  result: 'Відарна' },
      { min: 9,   max: 10, result: 'Нінсуну' },
      { min: 11,  max: 12, result: 'Балату' },
      { min: 13,  max: 14, result: 'Доросі' },
      { min: 15,  max: 16, result: 'Ґезера' },
      { min: 17,  max: 18, result: 'Зурсан' },
      { min: 19,  max: 20, result: 'Селіку' },
      { min: 21,  max: 22, result: 'Утамара' },
      { min: 23,  max: 24, result: 'Небакай' },
      { min: 25,  max: 26, result: 'Дісмашк' },
      { min: 27,  max: 28, result: 'Мітуну' },
      { min: 29,  max: 30, result: 'Атані' },
      { min: 31,  max: 32, result: 'Кінзура' },
      { min: 33,  max: 34, result: 'Сумула' },
      { min: 35,  max: 36, result: 'Укамес' },
      { min: 37,  max: 38, result: 'Амешкі' },
      { min: 39,  max: 40, result: 'Ілсіт' },
      { min: 41,  max: 42, result: 'Майятанай' },
      { min: 43,  max: 44, result: 'Етана' },
      { min: 45,  max: 46, result: 'Ґаманна' },
      { min: 47,  max: 48, result: 'Нессана' },
      { min: 49,  max: 50, result: 'Уралар' },
      { min: 51,  max: 52, result: 'Тішету' },
      { min: 53,  max: 54, result: 'Левсія' },
      { min: 55,  max: 56, result: 'Сутаге' },
      { min: 57,  max: 58, result: 'Дотані' },
      { min: 59,  max: 60, result: 'Уктанну' },
      { min: 61,  max: 62, result: 'Ретенай' },
      { min: 63,  max: 64, result: 'Кендалану' },
      { min: 65,  max: 66, result: 'Тахута' },
      { min: 67,  max: 68, result: 'Маттісса' },
      { min: 69,  max: 70, result: 'Анату' },
      { min: 71,  max: 72, result: 'Аралу' },
      { min: 73,  max: 74, result: 'Арахі' },
      { min: 75,  max: 76, result: 'Ібрахем' },
      { min: 77,  max: 78, result: 'Сіносу' },
      { min: 79,  max: 80, result: 'Джемшида' },
      { min: 81,  max: 82, result: 'Вісапні' },
      { min: 83,  max: 84, result: 'Хуллата' },
      { min: 85,  max: 86, result: 'Сідура' },
      { min: 87,  max: 88, result: 'Керіху' },
      { min: 89,  max: 90, result: 'Ерешкі' },
      { min: 91,  max: 92, result: 'Кібела' },
      { min: 93,  max: 94, result: 'Анунна' },
      { min: 95,  max: 96, result: 'Отані' },
      { min: 97,  max: 98, result: 'Дітані' },
      { min: 99,  max: 100, result: 'Фараза' },
    ],
  },
};

export default oracle;
