import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'settlement-trouble',
  title: { en: 'Settlement Trouble', uk: 'Проблема поселення' },
  description: {
    en: 'Use to generate a plot hook for a problem facing a community.',
    uk: 'Генерує сюжетний гачок — проблему спільноти.',
  },
  rows: {
    en: [
      { min: 1,  max: 2,  result: 'Outsiders rejected' },
      { min: 3,  max: 4,  result: 'Dangerous discovery' },
      { min: 5,  max: 6,  result: 'Dreadful omens' },
      { min: 7,  max: 8,  result: 'Natural disaster' },
      { min: 9,  max: 10, result: 'Old wounds reopened' },
      { min: 11, max: 12, result: 'Important object is lost' },
      { min: 13, max: 14, result: 'Someone is captured' },
      { min: 15, max: 16, result: 'Mysterious phenomenon' },
      { min: 17, max: 18, result: 'Revolt against a leader' },
      { min: 19, max: 20, result: 'Vengeful outcast' },
      { min: 21, max: 22, result: 'Rival settlement' },
      { min: 23, max: 24, result: 'Nature strikes back' },
      { min: 25, max: 26, result: 'Someone is missing' },
      { min: 27, max: 28, result: 'Production halts' },
      { min: 29, max: 30, result: 'Mysterious murders' },
      { min: 31, max: 32, result: 'Debt comes due' },
      { min: 33, max: 34, result: 'Unjust leadership' },
      { min: 35, max: 36, result: 'Disastrous accident' },
      { min: 37, max: 38, result: 'In league with the enemy' },
      { min: 39, max: 40, result: 'Raiders prey on the weak' },
      { min: 41, max: 42, result: 'Cursed past' },
      { min: 43, max: 44, result: 'An innocent is accused' },
      { min: 45, max: 46, result: 'Corrupted by dark magic' },
      { min: 47, max: 48, result: 'Isolated by brutal weather' },
      { min: 49, max: 50, result: 'Provisions are scarce' },
      { min: 51, max: 52, result: 'Sickness run amok' },
      { min: 53, max: 54, result: 'Allies become enemies' },
      { min: 55, max: 56, result: 'Attack is imminent' },
      { min: 57, max: 58, result: 'Lost caravan' },
      { min: 59, max: 60, result: 'Dark secret revealed' },
      { min: 61, max: 62, result: 'Urgent expedition' },
      { min: 63, max: 64, result: 'A leader falls' },
      { min: 65, max: 66, result: 'Families in conflict' },
      { min: 67, max: 68, result: 'Incompetent leadership' },
      { min: 69, max: 70, result: 'Reckless warmongering' },
      { min: 71, max: 72, result: 'Beast on the hunt' },
      { min: 73, max: 74, result: 'Betrayed from within' },
      { min: 75, max: 76, result: 'Broken truce' },
      { min: 77, max: 78, result: 'Wrathful haunt' },
      { min: 79, max: 80, result: 'Conflict with firstborn' },
      { min: 81, max: 82, result: 'Trade route blocked' },
      { min: 83, max: 84, result: 'In the crossfire' },
      { min: 85, max: 86, result: 'Stranger causes discord' },
      { min: 87, max: 88, result: 'Important event threatened' },
      { min: 89, max: 90, result: 'Dangerous tradition' },
      { min: 91, max: 100, result: 'Roll twice', rollAgain: 2 },
    ],
    uk: [
      { min: 1,  max: 2,  result: 'Відторгнення чужинців' },
      { min: 3,  max: 4,  result: 'Небезпечне відкриття' },
      { min: 5,  max: 6,  result: 'Моторошні знамення' },
      { min: 7,  max: 8,  result: 'Стихійне лихо' },
      { min: 9,  max: 10, result: 'Старі рани розкриваються' },
      { min: 11, max: 12, result: 'Важливий предмет втрачено' },
      { min: 13, max: 14, result: 'Когось захопили в полон' },
      { min: 15, max: 16, result: 'Загадкове явище' },
      { min: 17, max: 18, result: 'Бунт проти лідера' },
      { min: 19, max: 20, result: 'Мстивий вигнанець' },
      { min: 21, max: 22, result: 'Вороже поселення' },
      { min: 23, max: 24, result: 'Природа завдає удару у відповідь' },
      { min: 25, max: 26, result: 'Хтось зник безвісти' },
      { min: 27, max: 28, result: 'Зупинка виробництва' },
      { min: 29, max: 30, result: 'Загадкові вбивства' },
      { min: 31, max: 32, result: 'Настав час сплачувати борг' },
      { min: 33, max: 34, result: 'Несправедливе керівництво' },
      { min: 35, max: 36, result: 'Катастрофічна аварія' },
      { min: 37, max: 38, result: 'У змові з ворогом' },
      { min: 39, max: 40, result: 'Нападники полюють на слабких' },
      { min: 41, max: 42, result: 'Прокляте минуле' },
      { min: 43, max: 44, result: 'Невинного звинувачують' },
      { min: 45, max: 46, result: 'Спотворення темною магією' },
      { min: 47, max: 48, result: 'Ізольовано через жорстоку погоду' },
      { min: 49, max: 50, result: 'Нестача припасів' },
      { min: 51, max: 52, result: 'Хвороба вийшла з-під контролю' },
      { min: 53, max: 54, result: 'Союзники стають ворогами' },
      { min: 55, max: 56, result: 'Напад неминучий' },
      { min: 57, max: 58, result: 'Зниклий караван' },
      { min: 59, max: 60, result: 'Темна таємниця розкрита' },
      { min: 61, max: 62, result: 'Термінова експедиція' },
      { min: 63, max: 64, result: 'Лідер падає (або помирає)' },
      { min: 65, max: 66, result: 'Сім\'ї в конфлікті' },
      { min: 67, max: 68, result: 'Некомпетентне керівництво' },
      { min: 69, max: 70, result: 'Безрозсудне розпалювання війни' },
      { min: 71, max: 72, result: 'Звір вийшов на полювання' },
      { min: 73, max: 74, result: 'Зрада зсередини' },
      { min: 75, max: 76, result: 'Порушене перемир\'я' },
      { min: 77, max: 78, result: 'Гнівний привид' },
      { min: 79, max: 80, result: 'Конфлікт з Первородними' },
      { min: 81, max: 82, result: 'Торговельний шлях заблоковано' },
      { min: 83, max: 84, result: 'Під перехресним вогнем' },
      { min: 85, max: 86, result: 'Незнайомець сіє розбрат' },
      { min: 87, max: 88, result: 'Важлива подія під загрозою' },
      { min: 89, max: 90, result: 'Небезпечна традиція' },
      { min: 91, max: 100, result: 'Киньте двічі', rollAgain: 2 },
    ],
  },
};

export default oracle;
