import type { SimpleOracle } from './oracle-types';

const oracle: SimpleOracle = {
  kind: 'simple',
  id: 'ironlander-names',
  title: { en: 'Ironlander Names', uk: 'Імена залізоземців' },
  description: {
    en: 'Use to quickly generate a name for an Ironlander character. Names are often gender-neutral.',
    uk: 'Для швидкої генерації імені персонажа Залізоземця. Імена часто гендерно-нейтральні.',
  },
  entries: {
    en: [
      'Solana / Segura','Keelan / Gethin','Cadigan / Bataar','Sola / Basira','Kodroth / Joa',
      'Kione / Glynn','Katja / Toran','Tio / Arasen','Artiga / Kuron','Eos / Griff',
      'Bastien / Owena','Elli / Adda','Maura / Euros','Haleema / Kova','Abella / Kara',
      'Morter / Morgan','Wulan / Nanda','Mai / Tamara','Farina / Asha','Pearce / Delos',
      'Wynne / Torgan','Haf / Makari','Aeddon / Selva','Khinara / Kimura','Milla / Rhian',
      'Nakata / Tristan','Kynan / Siorra','Kiah / Sayer','Jaggar / Cortina','Beca / Vesna',
      'Ikram / Kataka','Melia / Keyshia','Sidan / Mila','Deshi / Lili','Tessa / Vigo',
      'Sibila / Sadia','Morien / Malik','Mona / Dag','Padma / Kuno','Avella / Reva',
      'Naila / Kai','Lio / Kalina','Cera / Jihan','Ithela / Hennion','Zhan / Abram',
      'Kaivan / Aida','Valeri / Myrtle','Hirsham / Nekun','Pemba / Menna','Edda / Tahir',
      'Lestara / Sarria','Lago / Nakura','Elstan / Akiya','Saskia / Talan','Kabeera / Mattick',
      'Caldas / Okoth','Nisus / Khulan','Serene / Verena','Chenda / Beltran','Themon / Del',
      'Erin / Ranna','Alban / Alina','Parcell / Muna','Jelma / Mura','Willa / Torrens',
      'Nadira / Yuda','Gwen / Nazmi','Amara / Ghalen','Masias / Sarda','Kanno / Shona',
      'Razeena / Kalidas','Mira / Wena','Perella / Sendra','Myrick / Kori','Qamar / Setara',
      'Kormak / Lucia','Zura / Maya','Zanita / Reema','Brynn / Yorath','Tegan / Rhoddri',
      'Pendry / Shekhar','Quinn / Servan','Fanir / Reese','Glain / Kenrick','Emelyn / Indirra',
      'Kendi / Giliana','Althus / Jebran','Leela / Kotama','Ishana / Fara','Flint / Katrin',
      'Delkash / Namba','Nia / Lona','Nan / Taylah','Keeara / Kato','Katania / Esra',
      'Morell / Eleri','Temir / Irsia','Bas / Kayu','Sabine / Bevan','Tallus / Chandra',
    ],
    uk: [
      'Солана / Сеґура','Кілан / Ґетін','Кадіґан / Батаар','Сола / Басіра','Кодрот / Джоа',
      'Кіоне / Ґлінн','Катя / Торан','Тіо / Арасен','Артіга / Курон','Еос / Ґріф',
      'Бастьєн / Овена','Еллі / Адда','Маура / Еврус','Халіма / Кова','Абелла / Кара',
      'Мортер / Морган','Вулан / Нанда','Май / Тамара','Фаріна / Аша','Пірс / Делос',
      'Вінн / Торган','Хаф / Макарі','Еддон / Сельва','Хінара / Кімура','Мілла / Ріан',
      'Наката / Трістан','Кінан / Сіорра','Кіа / Саєр','Джаґґар / Кортіна','Бека / Весна',
      'Ікрам / Катака','Мелія / Кіша','Сідан / Міла','Деші / Лілі','Тесса / Віґо',
      'Сібіла / Садія','Морієн / Малік','Мона / Даґ','Падма / Куно','Авелла / Рева',
      'Наїла / Кай','Ліо / Каліна','Кера / Джіхан','Ітела / Хенніон','Жан / Абрам',
      'Кайван / Аїда','Валері / Міртл','Хіршам / Некун','Пемба / Менна','Едда / Тахір',
      'Лестара / Саррія','Лаго / Накура','Елстан / Акія','Саскія / Талан','Кабіра / Маттік',
      'Калдас / Окот','Нісус / Хулан','Серен / Верена','Ченда / Белтран','Темон / Дел',
      'Ерін / Ранна','Албан / Аліна','Парселл / Муна','Джельма / Мура','Вілла / Торренс',
      'Надіра / Юда','Ґвен / Назмі','Амара / Ґален','Масіас / Сарда','Канно / Шона',
      'Разіна / Калідас','Міра / Вена','Перелла / Сендра','Майрік / Корі','Камар / Сетара',
      'Кормак / Лусія','Зура / Майя','Заніта / Ріма','Брінн / Йорат','Теґан / Роддрі',
      'Пендрі / Шекхар','Квінн / Серван','Фанір / Різ','Ґлейн / Кенрік','Емелін / Індірра',
      'Кенді / Ґіліана','Алтус / Джебран','Ліла / Котама','Ішана / Фара','Флінт / Катрін',
      'Делкаш / Намба','Ніа / Лона','Нан / Тайла','Кіара / Като','Катанія / Есра',
      'Морелл / Елері','Темір / Ірсія','Бас / Каю','Сабін / Беван','Таллус / Чандра',
    ],
  },
};

export default oracle;
