import type { RangeOracle } from './oracle-types';

const oracle: RangeOracle = {
  kind: 'range',
  id: 'character-goal',
  title: { en: 'Character Goal', uk: 'Ціль персонажа' },
  description: {
    en: 'Use to determine the primary motivation of an NPC or faction.',
    uk: 'Визначає основну мотивацію НПС або фракції.',
  },
  rows: {
    en: [
      { min: 1,  max: 3,  result: 'Obtain an object' },
      { min: 4,  max: 6,  result: 'Make an agreement' },
      { min: 7,  max: 9,  result: 'Build a relationship' },
      { min: 10, max: 12, result: 'Undermine a relationship' },
      { min: 13, max: 15, result: 'Seek a truth' },
      { min: 16, max: 18, result: 'Pay a debt' },
      { min: 19, max: 21, result: 'Refute a falsehood' },
      { min: 22, max: 24, result: 'Harm a rival' },
      { min: 25, max: 27, result: 'Cure an ill' },
      { min: 28, max: 30, result: 'Find a person' },
      { min: 31, max: 33, result: 'Find a home' },
      { min: 34, max: 36, result: 'Seize power' },
      { min: 37, max: 39, result: 'Restore a relationship' },
      { min: 40, max: 42, result: 'Create an item' },
      { min: 43, max: 45, result: 'Travel to a place' },
      { min: 46, max: 48, result: 'Secure provisions' },
      { min: 49, max: 51, result: 'Rebel against power' },
      { min: 52, max: 54, result: 'Collect a debt' },
      { min: 55, max: 57, result: 'Protect a secret' },
      { min: 58, max: 60, result: 'Spread faith' },
      { min: 61, max: 63, result: 'Enrich themselves' },
      { min: 64, max: 66, result: 'Protect a person' },
      { min: 67, max: 69, result: 'Protect the status quo' },
      { min: 70, max: 72, result: 'Advance status' },
      { min: 73, max: 75, result: 'Defend a place' },
      { min: 76, max: 78, result: 'Avenge a wrong' },
      { min: 79, max: 81, result: 'Fulfill a duty' },
      { min: 82, max: 84, result: 'Gain knowledge' },
      { min: 85, max: 87, result: 'Prove worthiness' },
      { min: 88, max: 90, result: 'Find redemption' },
      { min: 91, max: 92, result: 'Escape from something' },
      { min: 93, max: 95, result: 'Resolve a dispute' },
      { min: 96, max: 100, result: 'Roll twice', rollAgain: 2 },
    ],
    uk: [
      { min: 1,  max: 3,  result: 'Здобути предмет' },
      { min: 4,  max: 6,  result: 'Укласти угоду' },
      { min: 7,  max: 9,  result: 'Побудувати стосунки' },
      { min: 10, max: 12, result: 'Підірвати стосунки' },
      { min: 13, max: 15, result: 'Шукати істину' },
      { min: 16, max: 18, result: 'Сплатити борг' },
      { min: 19, max: 21, result: 'Спростувати брехню' },
      { min: 22, max: 24, result: 'Завдати шкоди супернику' },
      { min: 25, max: 27, result: 'Вилікувати хворобу' },
      { min: 28, max: 30, result: 'Знайти людину' },
      { min: 31, max: 33, result: 'Знайти дім' },
      { min: 34, max: 36, result: 'Захопити владу' },
      { min: 37, max: 39, result: 'Відновити стосунки' },
      { min: 40, max: 42, result: 'Створити предмет' },
      { min: 43, max: 45, result: 'Відправитися в певне місце' },
      { min: 46, max: 48, result: 'Здобути припаси' },
      { min: 49, max: 51, result: 'Повстати проти влади' },
      { min: 52, max: 54, result: 'Стягнути борг' },
      { min: 55, max: 57, result: 'Захистити таємницю' },
      { min: 58, max: 60, result: 'Поширювати віру' },
      { min: 61, max: 63, result: 'Збагатитися' },
      { min: 64, max: 66, result: 'Захистити людину' },
      { min: 67, max: 69, result: 'Захистити статус-кво' },
      { min: 70, max: 72, result: 'Підвищити статус' },
      { min: 73, max: 75, result: 'Захистити місце' },
      { min: 76, max: 78, result: 'Помститися за кривду' },
      { min: 79, max: 81, result: 'Виконати обов\'язок' },
      { min: 82, max: 84, result: 'Здобути знання' },
      { min: 85, max: 87, result: 'Довести свою гідність' },
      { min: 88, max: 90, result: 'Знайти спокуту' },
      { min: 91, max: 92, result: 'Втекти від чогось' },
      { min: 93, max: 95, result: 'Вирішити суперечку' },
      { min: 96, max: 100, result: 'Киньте двічі', rollAgain: 2 },
    ],
  },
};

export default oracle;
